version: v1.0
name: neetoCi
global_job_config:
  setup:
    - checkout
    - neetoci-version python 3.8
    - neetoci-service start mysql
    - sudo apt-get update && sudo apt-get install -y python3-dev default-libmysqlclient-dev
    - cache restore
    - pip download --cache-dir .pip_cache -r requirements.txt
    - cache store
    - pip install -r requirements.txt --cache-dir .pip_cache
  jobs:
    - name: Unit Test
      commands:
        - git ls-files | grep -v 'migrations' | grep -v 'settings.py' | grep -v 'manage.py' | grep -E '.py$' |
          xargs pylint -E --load-plugins=pylint_django
        - python manage.py test tasks.tests.test_models
        - python manage.py test tasks.tests.test_views
        - python manage.py check --deploy --fail-level ERROR
        - echo "Unit Test Completed"