version: v1.0
name: neetoCi
envs:
  - key: DB_NAME
    value: 'pydjango'
global_job_config:
  setup:
    - neetoci-version python 3.8
    - neetoci-service start mysql
    - sudo apt-get update && sudo apt-get install -y -qq mysql-client python3-dev default-libmysqlclient-dev
    - mysql --host=0.0.0.0 -uroot -e "create database $DB_NAME"
    - checkout
    - cache restore
    - pip download --cache-dir .pip_cache -r requirements.txt
    - cache store
    - pip install -r requirements.txt --cache-dir .pip_cache
    - nohup python manage.py runserver 127.0.0.1:8732 &
  jobs:
    - name: Unit Test
      commands:
        - git ls-files | grep -v 'migrations' | grep -v 'settings.py' | grep -v 'manage.py' | grep -E '.py$' |
          xargs pylint -E --load-plugins=pylint_django
        - python manage.py test tasks.tests.test_models
        - python manage.py test tasks.tests.test_views